### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by pwnllc** [mcore1976/antispy-jammer#2]

**Comment by mcore1976** [comment]
These are the components that I am using :

Transducers 25kHZ : https://www.aliexpress.com/item/1644831156.html

TPA3116D2 MONO module : https://www.aliexpress.com/item/1005004346789227.html

AD9833 module : https://www.aliexpress.com/item/1005005003429966.html

Digispark ATTINY85 board :  https://www.aliexpress.com/item/2040316211.html

Capacitors 50V / 0,33uF - 1uF  and 50V / 100-2200uF : https://www.aliexpress.com/item/1005005248323933.html

Cables : https://www.aliexpress.com/item/1005003172419981.html

Power source 12V : https://www.aliexpress.com/item/32798499158.html
